### Label Encoding is process of converting categorical label into numbers i.e. male = 0 & female = 1

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('/Users/jeettrivedi/Desktop/Data Science/Data Pre-Processing/Data/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

#### load the label encoder

In [10]:
label_encode = LabelEncoder()

In [17]:
labels = LabelEncoder().fit_transform(df.diagnosis)

#### appending labels to dataframe

In [18]:
df['target'] = labels
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32,target
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN,1
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN,1
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN,1
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN,1
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN,1
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN,1
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN,1
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN,1
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN,0

In [21]:
df['target'].value_counts()

0    357
1    212
Name: target, dtype: int64

In [4]:
iris = pd.read_csv('/Users/jeettrivedi/Desktop/Data Science/Data Pre-Processing/Data/iris_data.csv')

In [23]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

### Manual Label Encoding

In [24]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [34]:
iris['Species'].replace('Iris-setosa' ,0, inplace=True)
iris['Species'].replace('Iris-versicolor' ,1, inplace=True)
iris['Species'].replace('Iris-virginica' ,2, inplace=True)
iris

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [35]:
iris['Species'].value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

# <i>This is for interview question</i>

In [20]:
print(f'{iris.dtypes} \n')
print(f'{iris.dtypes.value_counts()} \n')

# Get only columns with datatype of float64

iris.select_dtypes(include=['float64'])

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

float64    4
int64      1
object     1
dtype: int64

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [101]:
iris.sample(n=40)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
107,108,7.3,2.9,6.3,1.8,Iris-virginica
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
141,142,6.9,3.1,5.1,2.3,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
25,26,5.0,3.0,1.6,0.2,Iris-setosa
126,127,6.2,2.8,4.8,1.8,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
27,28,5.2,3.5,1.5,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
35,36,5.0,3.2,1.2,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
146,147,6.3,2.5,5.0,1.9,Iris-virginica
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
42,43,4.4,3.2,1.3,0.2,Iris-setosa
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
46,47,5.1,3.8,1.6,0.2,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
110,111,6.5,3.2,5.1,2.0,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
29,30,4.7,3.2,1.6,0.2,Iris-setosa
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
129,130,7.2,3.0,5.8,1.6,Iris-virginica
0,1,5.1,3.5,1.4,0.2,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
114,115,5.8,2.8,5.1,2.4,Iris-virginica
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
105,106,7.6,3.0,6.6,2.1,Iris-virginica

In [112]:
a = ['Jeet','Dev','Ajay']
b = ['Trivedi','Raval','Pandey']
b = [' ' + x  for x in b]
c = []
for i in range(len(a)):
    print(a[i])
    print(b[i])
    c.append(a[i]+b[i])
    
c

Jeet
 Trivedi
Dev
 Raval
Nidhi
 Pandey

['Jeet Trivedi', 'Dev Raval', 'Nidhi Pandey']

In [115]:
a = ['Jessy','Donald','Nela']
b = ['Robert','Trump','Hunt']
c= []
for i,j in zip(a,b):
    name = i+' '+j
    c.append(name)

c

['Jessy Robert', 'Donald Trump', 'Nela Hunt']